name: Docker Image and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare image list
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.read.outputs.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: read
        name: Read images config
        run: |
          echo "images=<<EOF" >> $GITHUB_OUTPUT
          cat build-config.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  build-and-push:
    name: Build and Push Images
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.prepare.outputs.images) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Information
        run: |
          echo "Building image: ${{ matrix.image }}"
          echo "Files:"
          ls -lah
      - name: Get tags
        run: git fetch --tags origin
      - name: Docker QEMU
        uses: docker/setup-qemu-action@v3.3.0
      - name: Buildx Setup
        uses: docker/setup-buildx-action@v3.8.0
        with:
          use: true
      - name: Login to Docker
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Build & Publish
      - name: Build & Publish Docker Image
        run: BUILDX_ARGS="--cache-from=gha --cache-to=gha,mode=max --progress=plain" PUSH=1 MULTIARCH=1 REGISTRY=${{ secrets.DOCKER_USERNAME }} PUSH=1 bash builder.sh ${{ matrix.image.path }} ${{ matrix.image.name }} ${{ matrix.image.dockerfile || 'Dockerfile' }} ${{ matrix.image.tag || 'latest'}}